all: hello/TCPlocalclient hello/TCPlocalserver hello/UDPlocalserver hello/UDPlocalclient

hello/TCPlocalclient: hello/TCPlocalclient.c
	gcc $< -o $@

hello/TCPlocalserver: hello/TCPlocalserver.c
	gcc $< -o $@

hello/UDPlocalserver: hello/UDPlocalserver.c
	gcc $< -o $@

hello/UDPlocalclient: hello/UDPlocalclient.c
	gcc $< -o $@